"""
AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
"""

import os
import requests


SYSTEM_PROMPT = """你是一个专业的 AI 行业资讯编辑。你的任务是将收集到的原始 AI 资讯整理成一份高质量的每日简报。

要求：
1. 从提供的原始内容中筛选出最有价值的 10-15 条资讯
2. 去除重复和低质量内容
3. 每条资讯用 2-3 句话总结，保留关键信息（谁、做了什么、为什么重要）
4. 按类别分组：📰 行业新闻 / 📄 重要论文 / 🔧 开源项目
5. 在末尾加一段 "今日观察"（3-5 句话），点评今天 AI 领域的整体动态
6. 所有内容必须基于提供的原始素材，不要编造
7. 输出格式为 Markdown
8. 用中文输出，专有名词保留英文
"""


def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []

    if data.get("news"):
        sections.append("=== 新闻资讯 ===")
        for item in data["news"]:
            sections.append(f"[{item['source']}] {item['title']}\nURL: {item['url']}\n{item['summary']}\n")

    if data.get("papers"):
        sections.append("=== 学术论文 ===")
        for item in data["papers"]:
            sections.append(f"{item['title']}\nURL: {item['url']}\n{item['summary']}\n")

    if data.get("projects"):
        sections.append("=== 开源项目 ===")
        for item in data["projects"]:
            sections.append(f"{item['title']}\nURL: {item['url']}\n{item['summary']}\n")

    return "\n".join(sections)


def summarize(data, date_str):
    """Generate daily digest via OpenAI-compatible API (DeepSeek by default)."""
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return f"# AI Daily Digest - {date_str}\n\n> No content fetched today.\n"

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的 AI 领域原始资讯，请整理成每日简报：

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 4096,
    }

    print(f"Calling {model}...")
    resp = requests.post(url, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()

    result = resp.json()
    text = result["choices"][0]["message"]["content"]

    markdown = f"""# AI Daily Digest - {date_str}

{text}

---
*Generated by AI Daily Digest using {model}*
"""
    return markdown
