"""
AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
"""

import os
import requests


SYSTEM_PROMPT = """你是一位 AI 领域的资深编辑，面向 AI 从业者、研究者和开发者输出每日简报。

【筛选标准】优先选择以下类型的内容，其余的直接丢弃：
- 重大模型/产品发布（GPT、Claude、Gemini、Llama、Mistral 等）
- 技术突破（新架构、推理加速、重要 benchmark）
- 开源项目（GitHub 高 star、有实际使用价值）
- 产业动向（大厂战略、重要融资/并购、政策监管）
- 前沿研究（HuggingFace 精选论文）
- Hacker News 社区热点（技术圈真实关注点）

【丢弃标准】以下内容不要纳入：
- 无实质内容的观点文章、预测类文章
- 重复或高度相似的报道（只保留最详细的一条）
- 炒作性标题但无具体细节的文章

【输出要求】
1. 总计 10-15 条，按类别分组：📰 行业新闻 / 📄 重要论文 / 🔧 开源项目
2. 每条格式固定如下（严格遵守）：
- **[标题]**：一句话说清楚发生了什么。
  - 重要性：★★★★☆ / 5
  - 核心价值：对开发者/研究者/产品的具体影响是什么（不超过 30 字）
  - 来源：[Source Name](URL)
3. 末尾"今日观察"：3-4 句话，点出今天最值得关注的趋势或信号，有观点，不废话
4. 严格基于原文，不编造，专有名词保留英文，其余用中文
"""


def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []

    if data.get("news"):
        sections.append("=== 新闻资讯 ===")
        for item in data["news"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("papers"):
        sections.append("=== 学术论文 ===")
        for item in data["papers"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("projects"):
        sections.append("=== 开源项目 ===")
        for item in data["projects"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    return "\n".join(sections)


def summarize(data, date_str):
    """Generate daily digest via OpenAI-compatible API (DeepSeek by default)."""
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return f"# AI Daily Digest - {date_str}\n\n> No content fetched today.\n"

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的 AI 领域原始资讯，请整理成每日简报。
请优先选择重要性高、来源可靠、对 AI builder 有实际参考价值的内容：

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 4096,
    }

    print(f"Calling {model}...")
    resp = requests.post(url, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()

    result = resp.json()
    text = result["choices"][0]["message"]["content"]

    markdown = f"""# AI Daily Digest - {date_str}

{text}

---
*Generated by AI Daily Digest using {model}*
"""
    return markdown
